<?php

return [

    [
        'id' => 1,
        'nama' => 'Tas Anyaman Rotan',
        'gambar' => 'tas-rotan.jpg',
        'kategori' => 'Kerajinan',
        'harga' => 125000,
        'deskripsi' => 'Tas handmade berkualitas tinggi dari rotan pilihan.',
        'deskripsi_lengkap' => 'Tas anyaman rotan dibuat secara handmade oleh pengrajin lokal menggunakan bahan rotan berkualitas tinggi. Cocok digunakan untuk aktivitas sehari-hari maupun acara formal.',
        'umkm' => 'Rotan Jaya',
        'alamat' => 'Yogyakarta',
        'whatsapp' => '6281234567890',
    ],

    [
        'id' => 2,
        'nama' => 'Keripik Pisang Original',
        'gambar' => 'keripik-pisang.jpg',
        'kategori' => 'Makanan',
        'harga' => 25000,
        'deskripsi' => 'Keripik pisang renyah tanpa bahan pengawet.',
        'deskripsi_lengkap' => 'Keripik dibuat dari pisang pilihan dengan rasa gurih dan renyah tanpa bahan pengawet.',
        'umkm' => 'Pisang Makmur',
        'alamat' => 'Bandung',
        'whatsapp' => '6282233445566',
    ],

    [
        'id' => 3,
        'nama' => 'Kopi Arabica Gayo',
        'gambar' => 'kopi-gayo.jpg',
        'kategori' => 'Minuman',
        'harga' => 75000,
        'deskripsi' => 'Kopi premium khas Aceh.',
        'deskripsi_lengkap' => 'Kopi Arabica Gayo memiliki aroma khas, body yang kuat dan cita rasa fruity yang disukai pecinta kopi.',
        'umkm' => 'Kopi Nusantara',
        'alamat' => 'Aceh',
        'whatsapp' => '6289876543210',
    ],

    [
        'id' => 4,
        'nama' => 'Dompet Kulit Handmade',
        'gambar' => 'dompet-kulit.jpg',
        'kategori' => 'Fashion',
        'harga' => 180000,
        'deskripsi' => 'Dompet kulit asli dengan jahitan premium.',
        'deskripsi_lengkap' => 'Menggunakan kulit sapi asli berkualitas dengan jahitan rapi dan tahan lama.',
        'umkm' => 'Leather Craft',
        'alamat' => 'Garut',
        'whatsapp' => '6282211112222',
    ],

    [
        'id' => 5,
        'nama' => 'Cheesecuit',
        'gambar' => 'chesscuit.jpeg',
        'kategori' => 'Makanan',
        'harga' => 65000,
        'deskripsi' => 'hidangan penutup (dessert) .',
        'deskripsi_lengkap' => 'hidangan penutup (dessert).',
        'umkm' => 'Aroma Home',
        'alamat' => 'Malang',
        'whatsapp' => '6285512345678',
    ],

    [
        'id' => 6,
        'nama' => 'Batik Tulis Premium',
        'gambar' => 'batik.jpg',
        'kategori' => 'Fashion',
        'harga' => 350000,
        'deskripsi' => 'Batik tulis motif klasik.',
        'deskripsi_lengkap' => 'Batik tulis premium hasil karya pengrajin berpengalaman dengan motif khas Indonesia.',
        'umkm' => 'Batik Heritage',
        'alamat' => 'Solo',
        'whatsapp' => '6288899001122',
    ],

    [
        'id' => 7,
        'nama' => 'Madu Hutan Asli',
        'gambar' => 'madu.jpg',
        'kategori' => 'Makanan',
        'harga' => 95000,
        'deskripsi' => '100% madu hutan tanpa campuran.',
        'deskripsi_lengkap' => 'Dipanen langsung dari hutan alami sehingga menghasilkan madu murni berkualitas tinggi.',
        'umkm' => 'Madu Sehat',
        'alamat' => 'Kalimantan',
        'whatsapp' => '6289911223344',
    ],

    [
        'id' => 8,
        'nama' => 'Sandal Kulit Pria',
        'gambar' => 'sandal.jpg',
        'kategori' => 'Fashion',
        'harga' => 145000,
        'deskripsi' => 'Sandal kulit nyaman untuk aktivitas sehari-hari.',
        'deskripsi_lengkap' => 'Menggunakan kulit asli dengan desain modern dan sol anti slip.',
        'umkm' => 'Leather Shoes',
        'alamat' => 'Magetan',
        'whatsapp' => '6288877665544',
    ],

    [
        'id' => 9,
        'nama' => 'Vas Keramik',
        'gambar' => 'vas.jpg',
        'kategori' => 'Dekorasi',
        'harga' => 120000,
        'deskripsi' => 'Vas keramik handmade.',
        'deskripsi_lengkap' => 'Vas keramik dengan desain minimalis yang cocok untuk mempercantik ruangan.',
        'umkm' => 'Keramik Indah',
        'alamat' => 'Kasongan',
        'whatsapp' => '6287712345678',
    ],

    [
        'id' => 10,
        'nama' => 'Kaos Sablon Lokal',
        'gambar' => 'kaos.jpeg',
        'kategori' => 'Fashion',
        'harga' => 89000,
        'deskripsi' => 'Kaos cotton combed 30s.',
        'deskripsi_lengkap' => 'Kaos berkualitas tinggi dengan desain eksklusif dan nyaman digunakan sehari-hari.',
        'umkm' => 'Creative Wear',
        'alamat' => 'Bandung',
        'whatsapp' => '6282212345678',
    ],

    [
        'id' => 11,
        'nama' => 'Teh Herbal Rosella',
        'gambar' => 'teh.jpg',
        'kategori' => 'Minuman',
        'harga' => 45000,
        'deskripsi' => 'Teh herbal kaya antioksidan.',
        'deskripsi_lengkap' => 'Teh herbal dari bunga rosella pilihan tanpa bahan pengawet.',
        'umkm' => 'Herbal Nusantara',
        'alamat' => 'Semarang',
        'whatsapp' => '6286612345678',
    ],

    [
        'id' => 12,
        'nama' => 'Jam Dinding Kayu',
        'gambar' => 'jam.jpg',
        'kategori' => 'Dekorasi',
        'harga' => 160000,
        'deskripsi' => 'Jam dinding kayu jati.',
        'deskripsi_lengkap' => 'Jam dinding berbahan kayu jati dengan desain elegan dan cocok untuk rumah maupun kantor.',
        'umkm' => 'Wood Craft',
        'alamat' => 'Jepara',
        'whatsapp' => '6285511122233',
    ],

];